name: "Check Agent Docs"
description: "Uses Claude Code to verify AGENTS.md and CLAUDE.md are up-to-date. Adds labels and comments on PRs based on freshness score."

inputs:
  anthropic-api-key:
    description: "Anthropic API key for Claude Code (direct API access)"
    required: false
  claude-code-oauth-token:
    description: "Claude Code OAuth token from /install-github-app (alternative to API key)"
    required: false
  doc-files:
    description: "Comma-separated list of doc files to check"
    required: false
    default: "AGENTS.md,CLAUDE.md,.claude/CLAUDE.md"
  model:
    description: "Claude model to use"
    required: false
    default: "claude-sonnet-4-20250514"
  threshold-blocking:
    description: "Score below this (0-100) adds blocking label and fails check"
    required: false
    default: "30"
  threshold-warning:
    description: "Score below this (0-100) adds warning label"
    required: false
    default: "75"
  label-blocking:
    description: "Label to add when docs are severely outdated (can be used with pr-label-check)"
    required: false
    default: "agent-docs-outdated"
  label-warning:
    description: "Label to add when docs need minor updates"
    required: false
    default: "agent-docs-stale"
  github-token:
    description: "GitHub token for API access (needs issues/PRs write permission)"
    required: false
    default: ${{ github.token }}

outputs:
  skipped:
    description: "Whether the check was skipped due to missing configuration"
    value: ${{ steps.check-config.outputs.skipped }}
  score:
    description: "Documentation freshness score (0-100)"
    value: ${{ steps.parse-result.outputs.score }}
  status:
    description: "Status: pass, warning, or blocking"
    value: ${{ steps.parse-result.outputs.status }}
  label-added:
    description: "Label that was added (if any)"
    value: ${{ steps.parse-result.outputs.label }}

runs:
  using: "composite"
  steps:
    - name: Check configuration
      id: check-config
      shell: bash
      env:
        HAS_API_KEY: ${{ inputs.anthropic-api-key != '' }}
        HAS_OAUTH_TOKEN: ${{ inputs.claude-code-oauth-token != '' }}
      run: |
        if [ "$HAS_API_KEY" != "true" ] && [ "$HAS_OAUTH_TOKEN" != "true" ]; then
          echo "::warning::Check Agent Docs: No auth configured. Provide anthropic-api-key or claude-code-oauth-token. Run '/install-github-app' in Claude Code to set up."
          echo "skipped=true" >> "$GITHUB_OUTPUT"
        else
          echo "skipped=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Find doc files
      if: steps.check-config.outputs.skipped == 'false'
      id: find-docs
      shell: bash
      run: |
        IFS=',' read -ra DOC_FILES <<< "${{ inputs.doc-files }}"
        found_files=""
        for file in "${DOC_FILES[@]}"; do
          file=$(echo "$file" | xargs)
          if [ -f "$file" ]; then
            if [ -n "$found_files" ]; then
              found_files="$found_files, $file"
            else
              found_files="$file"
            fi
          fi
        done

        if [ -z "$found_files" ]; then
          echo "::notice::No agent doc files found in repository. Skipping check."
          echo "has-docs=false" >> "$GITHUB_OUTPUT"
        else
          echo "Found doc files: $found_files"
          echo "has-docs=true" >> "$GITHUB_OUTPUT"
          echo "files=$found_files" >> "$GITHUB_OUTPUT"
        fi

    - name: Run Claude Code check
      if: steps.check-config.outputs.skipped == 'false' && steps.find-docs.outputs.has-docs == 'true'
      id: run-check
      uses: anthropics/claude-code-action@v1
      with:
        prompt: |
          You are checking if the agent documentation files are up-to-date with the codebase.
          This is running on a Pull Request, so comment your findings on the PR.

          ## Files to check
          ${{ steps.find-docs.outputs.files }}

          ## Your task
          1. Read each documentation file listed above
          2. Explore the codebase to understand the actual structure, commands, and conventions
          3. Compare the documentation against reality
          4. Score the documentation freshness from 0-100%

          ## Scoring criteria
          - 100%: Documentation is fully accurate, all commands/paths/structures match reality
          - 75-99%: Minor issues (typos, slightly outdated examples, missing optional info)
          - 30-74%: Moderate issues (missing sections, some incorrect commands/paths)
          - 0-29%: Severely outdated (wrong structure, broken commands, misleading info)

          ## What to check
          - Directory structure matches what's documented
          - Commands listed actually work (check package.json scripts, Makefile, etc.)
          - File paths and patterns mentioned still exist
          - Conventions described match actual code patterns
          - Any new important files/directories that should be documented

          ## Required output format
          You MUST comment on the PR with your findings using this exact format:

          ```
          ## Agent Docs Freshness Check

          **Score: [X]%** [emoji based on score: ✅ for 75+, ⚠️ for 30-74, 🔴 for <30]

          ### Summary
          [One sentence summary]

          ### Issues Found
          [Bulleted list of specific issues, or "None" if score is 100%]

          ### Suggested Fixes
          [Bulleted list of specific fixes needed, or "None needed" if score is 100%]

          ---
          <!-- AGENT_DOCS_SCORE:[X] -->
          ```

          The HTML comment at the end is required for automated parsing. Replace [X] with the numeric score.
        claude_args: "--model ${{ inputs.model }}"
        claude_code_oauth_token: ${{ inputs.claude-code-oauth-token }}
        github_token: ${{ inputs.github-token }}
      env:
        ANTHROPIC_API_KEY: ${{ inputs.anthropic-api-key }}

    - name: Parse result and apply labels
      if: steps.check-config.outputs.skipped == 'false' && steps.find-docs.outputs.has-docs == 'true'
      id: parse-result
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        THRESHOLD_BLOCKING: ${{ inputs.threshold-blocking }}
        THRESHOLD_WARNING: ${{ inputs.threshold-warning }}
        LABEL_BLOCKING: ${{ inputs.label-blocking }}
        LABEL_WARNING: ${{ inputs.label-warning }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
      run: |
        # Get the PR comments to find the score
        if [ -z "$PR_NUMBER" ]; then
          echo "Not running on a PR, skipping label management"
          echo "score=unknown" >> "$GITHUB_OUTPUT"
          echo "status=skipped" >> "$GITHUB_OUTPUT"
          echo "label=" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        # Fetch recent comments to find the score
        COMMENTS=$(gh pr view "$PR_NUMBER" --json comments --jq '.comments[-5:][].body' 2>/dev/null || echo "")

        # Extract score from the HTML comment marker
        SCORE=$(echo "$COMMENTS" | grep -oP 'AGENT_DOCS_SCORE:\K[0-9]+' | tail -1 || echo "")

        if [ -z "$SCORE" ]; then
          echo "Could not parse score from Claude's comment"
          echo "score=unknown" >> "$GITHUB_OUTPUT"
          echo "status=unknown" >> "$GITHUB_OUTPUT"
          echo "label=" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        echo "Parsed score: $SCORE"
        echo "score=$SCORE" >> "$GITHUB_OUTPUT"

        # Remove existing agent-docs labels first
        gh pr edit "$PR_NUMBER" --remove-label "$LABEL_BLOCKING" 2>/dev/null || true
        gh pr edit "$PR_NUMBER" --remove-label "$LABEL_WARNING" 2>/dev/null || true

        # Determine status and apply appropriate label
        if [ "$SCORE" -lt "$THRESHOLD_BLOCKING" ]; then
          echo "status=blocking" >> "$GITHUB_OUTPUT"
          echo "label=$LABEL_BLOCKING" >> "$GITHUB_OUTPUT"
          gh pr edit "$PR_NUMBER" --add-label "$LABEL_BLOCKING"
          echo "::error::Agent docs freshness score ($SCORE%) is below blocking threshold ($THRESHOLD_BLOCKING%). Update documentation before merging."
          exit 1
        elif [ "$SCORE" -lt "$THRESHOLD_WARNING" ]; then
          echo "status=warning" >> "$GITHUB_OUTPUT"
          echo "label=$LABEL_WARNING" >> "$GITHUB_OUTPUT"
          gh pr edit "$PR_NUMBER" --add-label "$LABEL_WARNING"
          echo "::warning::Agent docs freshness score ($SCORE%) is below warning threshold ($THRESHOLD_WARNING%). Consider updating documentation."
        else
          echo "status=pass" >> "$GITHUB_OUTPUT"
          echo "label=" >> "$GITHUB_OUTPUT"
          echo "Agent docs freshness score ($SCORE%) is good."
        fi
